Improved pre-commit a bit.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+echo "Building... "
 go build -o .lmk github.com/jeady/lmk/lmk >/dev/null 2>&1
 if [ $? -ne 0 ]
 then
@@ -10,6 +11,7 @@ then
 fi
 rm .lmk
 
+echo "Testing..."
 go test github.com/jeady/lmk/... >/dev/null 2>&1
 if [ $? -ne 0 ]
 then
@@ -18,6 +20,7 @@ then
   exit 1
 fi
 
+echo "Vetting..."
 go vet github.com/jeady/lmk/... >/dev/null 2>&1
 if [ $? -ne 0 ]
 then
@@ -33,21 +36,24 @@ fi
 # Copyright 2012 The Go Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style
 # license.
-
+echo "Linting..."
 gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
-[ -z "$gofiles" ] && exit 0
-
-unformatted=$(gofmt -tabs=false -tabwidth=2 -l $gofiles)
-if [ -n "$unformatted" ]
+if [ -z "$gofiles" ]
 then
-  # Some files are not gofmt'd. Print message and fail.
+  echo "No .go files to be committed."
+else
+  unformatted=$(gofmt -tabs=false -tabwidth=2 -l $gofiles)
+  if [ -n "$unformatted" ]
+  then
+    # Some files are not gofmt'd. Print message and fail.
 
-  echo >&2 "Go files must be formatted with gofmt. Please run:"
-  for fn in $unformatted; do
-    echo >&2 "  gofmt -w -tabs=false -tabwidth=2 $PWD/$fn"
-  done
+    echo >&2 "Go files must be formatted with gofmt. Please run:"
+    for fn in $unformatted; do
+      echo >&2 "  gofmt -w -tabs=false -tabwidth=2 $PWD/$fn"
+    done
 
-  exit 1
+    exit 1
+  fi
 fi
 
 echo "All pre-commit checks have passed."
